telegram:
  token: 5002376839:AAE2kZx7qOiLzUTNodzW5ixLT8MPxOTGnHA      # Telegram bot tokens look like this: 113031530:AAH_4c5Gt9gsVu82OVNjUV7poU7PodYiNsA
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
discord:
  useNickname: false
  token: OTMzMzY3MTAxNjQzNjk0MTIx.Yegf2g.DOYK1Xe_Rj-cQzlwimIMibmIwyA       # Discord bot tokens look like this: MjI3MDA1NzIvOBQ2MzAzMiMz.DRf-aw.N0MVYtDxXYPSQew4g2TPqvQve2c
  skipOldMessages: true
  replyLength: 100
  maxReplyLines: 2
bridges:
  - name: First bridge
    direction: both
    telegram:
      chatId: -1624548353 # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '850274256872538114'       # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: true
      relayLeaveMessages: true
      sendUsernames: true
      crossDeleteOnTelegram: true
debug: false
